version: '3'

services:
  website:
    container_name: website
    build: ./website
    volumes:
      - ./website:/var/www/html
    ports:
      - 5011:80
    depends_on:
      - database

  database:
    container_name: database
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306